### PR TITLE
Add ability to Donate and Support the project

### PR DESCRIPTION
**Pull request by Elijas**
@pmb6tz I'd like this project to have a Sponsor button. If you'd want to have to have a discussion about this first, please write an email to me (visible on my profile).

# Demo
[This is](https://github.com/Elijas/windows-desktop-switcher) how it will look once merged and activated

# After merging
This tick in the settings needs to be activated
image

### CODE REVIEW

**Comment by GrandTourism** [comment]
Yes! Must be this button !
Your script GREAT!

**Comment by Elijas** [comment]
> Yes! Must be this button !
> Your script GREAT!

We're glad you're enjoying our script!

We are currently 2 core developers, me and @pmb6tz. You can donate to the project already though https://ko-fi.com/elijas and the funds will be split 50/50 - just mention it's towards the Window Switcher support and development.

Thank you very much!

**Comment by GrandTourism** [comment]
Elijas, thank you! I bought some coffee))


ср, 14 окт. 2020 г. в 12:06, Elijas Dapšauskas <notifications@github.com>:

**Comment by pmb6tz** [comment]
Sent you a mail

**Review by pmb6tz — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
