### PR TITLE
Pin all desktops

### PR DESCRIPTION
**Pull request by Elijas**
I've also added ability to pin a window on top of other windows (so that the window doesn't hide beneath other windows when the focus is lost)
I think this works really well in tandem with the "pin on all desktops"

### CODE REVIEW

**Comment by pmb6tz** [comment]
Oddly enough, again, I can't get the pin to all desktops functionality to work either (I do see the message, but it doesn't actually pin). I have several different machines that I can image to try this out. I'm a bit worried that this functionality might not be as baked as we want...

**Comment by Elijas** [comment]
> Oddly enough, again, I can't get the pin to all desktops functionality to work either (I do see the message, but it doesn't actually pin). I have several different machines that I can image to try this out. I'm a bit worried that this functionality might not be as baked as we want...

That's bizzare, I'm on Windows 10 1803, it seems to works fine.
image

However, I have to continue work on some other projects, so unfortunately, I won't be able to spend time investigating these further, but let me know if there anything I could help!

**Comment by pmb6tz** [comment]
Unfortunately all of my machines are running 1809 - and all of them hit the same issue. Maybe the latest update breaks some of the DLL functionality..

**Comment by rajlego** [comment]
Unfortunately also not working for me on 1809. Would be huge help if it gets fixed. Though pin on top is working fine for me.

**Pull request closed without merging**
