### PR TITLE
Get Session ID

### LINKED ISSUE #6: SessionInfo is not always 1
If you sign out and then sing in again, there won't be reg key at `...\SessionInfo\1\...`, it will be `...\SessionInfo\2\...`.

### PR DESCRIPTION
**Pull request by Perlence**
Resolves #6.

### CODE REVIEW

**Comment by Perlence** [comment]
Please, feel free to squash commits.

**Comment by hawkins** [comment]
If no one objects, I think squashing these commits then merging the PR would be good.  This is a fix I've already benefited from, and I'm sure many future users would too.

**Comment by Perlence** [comment]
@hawkins Do you mind if I squash branch and commit it directly upstream, since I already have permissions of a collaborator? I'll just close this PR then.

**Comment by hawkins** [comment]
Sounds good to me! Just comment on this PR with the commit hash, please, so we can see how the commit and PR are related on GitHub.

**Comment by Perlence** [comment]
Squashed in 2e0d5d3517f3f783921775b4e9fc0da22d04943e.

**Comment by Perlence** [comment]
Ah, I missed a great opportunity to close this PR via commit message. Yeah, whatever.

**Pull request closed without merging**
