### PR TITLE
Restore active window after switching

### PR DESCRIPTION
**Pull request by Elijas**
Continuation on the previous pull request https://github.com/pmb6tz/windows-desktop-switcher/pull/19

### Setup 
Switching straight between Desktop 5 and 1. Real time gifs recorded at 60fps. Note, that the gif ends on the exact color where it started (so as that gif restarting would not be mistaken with the desktops switching).

2018-12-08_17h23_00

---

### Old:
gif2

---

### New:
gif

### CODE REVIEW

**Comment by Elijas** [comment]
@pmb6tz Could you comment on the state of this PR?

**Comment by pmb6tz** [comment]
I took a quick look; the main concern I have is that this change will require AHK version 1.1 or later. I'm not too keen on requiring the .dll, but we can give it a shot for now.. Appreciate your contribution!

Can you add a note to the readme that highlights that version 1.1 or later of AHK is required (in the installation steps?).

Also, I see that your PR should also restore foreground window focus when coming back to a desktop. What's the best way to test this?

**Comment by Elijas** [comment]
No problem, it's your repo - feel free to steer it where you envision :)

Testing is simple - have an active window (it's borders and title are highlighted), then switch to other desktop then switch back - without the fix your original window won't be active (since the taskbar is still activated)

Regarding the ahk - I didn't even have to take additional steps to use ahk 1.1 - just downloaded the latest version and I am good to go - although I understand the need to mention the supported version.

**Comment by pmb6tz** [comment]
All I meant is that the required AHK version must be 1.1 or later (I had to update to test your PR). I think this is OK, just want to have a note. I think I'll just accept the PR for now and update the readme. Thanks!

**Comment by pmb6tz** [comment]
Actually, what's the deal with the license? Is that required because of the DLL?

**Comment by Elijas** [comment]
> Actually, what's the deal with the license? Is that required because of the DLL?

I'm new to this licencing thing, but I've added them to help the PR comply with both of these MIT Licenses, as the code is based on them
https://github.com/Ciantic/VirtualDesktopAccessor/blob/master/LICENSE.txt
https://github.com/sdias/win-10-virtual-desktop-enhancer/blob/master/LICENSE

Although feel free to do as you will ;)

**Pull request merged**
