### PR TITLE
Added Numpad Equivalent

### PR DESCRIPTION
**Pull request by H0R1Z0N**
I added a numpad option for the key, they seem to work on my setup. Small change who help a lot for those with full size keyboard or with external numpad.

### CODE REVIEW

**Comment by Elijas** [comment]
@h0r1z0n, thank you for contributing, much appreciated! 

@pmb6tz I think it's great that numpad users get to use additional method for switching out of the box, this also comes handy for switching to the desktops further from the caps lock (5<)
The downside might be that the repo gets a little larger, and the instructions might get a little more complex. 

If we merge this, we should update the README too (i could do it) 

If we put a hold on the merge, we should at least give these changes as examples of customization in the README. (i could do it) 

I am neutral on the decision, though.

**Comment by Elijas** [comment]
@H0R1Z0N Thanks again, well written PR, spacing and all 🙂 Let's merge

**Review by Elijas — COMMENTED** [review]
[deleted]

**Review by Elijas — COMMENTED** [review]
[deleted]

**Comment by pmb6tz** [comment]
Just got around to this, LGTM, thanks for contributing!

**Comment by H0R1Z0N** [comment]
You are welcome

**Pull request merged**
